version: "3.8"

services:
  shop_on_go_container:
    build: .
    container_name: shop_on_go_container
    command: ./wait-for-db.sh ./shop_on_go "migrate"
    depends_on:
      - postgres
      - kafka
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - shopongo_default

  test:
    image: golang:1.23
    container_name: shop_on_go_test
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    command: go test ./...
    networks:
      - shopongo_default

  postgres:
    image: postgres:16.4
    container_name: go_shop_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    ports:
      - "5432:5432"
    networks:
      - shopongo_default

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - shopongo_default

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: kafka-zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_LOG4J_PROP=ERROR,CONSOLE
    volumes:
      - zookeeper-volume:/bitnami
      - ./pkg/kafkaService/logback.xml:/opt/bitnami/zookeeper/conf/logback.xml:ro
    networks:
      - shopongo_default

  kafka:
    image: docker.io/bitnami/kafka:3.3
    container_name: kafka
    restart: always
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_LOG4J_LOGGERS=root=ERROR,org.apache.kafka=ERROR
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    volumes:
      - kafka-volume:/bitnami
      - ./pkg/kafkaService/log4j.properties:/opt/bitnami/kafka/config/log4j.properties:ro
    networks:
      - shopongo_default

networks:
  shopongo_default:

volumes:
  kafka-volume:
  zookeeper-volume:
