version: "3.8"
services:

  shop_on_go_container:
    container_name: shop_on_go_container
    build: ./
    command: ./wait-for-db.sh ./shop_on_go "migrate"
    depends_on:
      - postgres
    ports:
      - "8081:8081"

  postgres:
    container_name: go_shop_postgres
    image: postgres:16.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    ports:
      - "5432:5432"
  redis:
    container_name: redis_container
    image: redis:latest
    restart: always
    environment:
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
