name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout review-proto
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: make install
      - name: Build
        run: |
          docker-compose build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Checkout review-proto
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: make install
      - name: Test
        run: |
          docker-compose run --rm search-service make test