name: CI Auth

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-template:
    uses: ./.github/workflows/ci-template.yml
    with:
      service_name: auth-service
      dockerfile_path: ./Dockerfile
      docker_context: .
      env_secret: ${{ secrets.APP_ENV_FILE }}
